name: AddHearts
version: '1.4.1'
main: com.gh05typlayz.AddHearts.Main
api-version: 1.19
author: GH05TYPLAYz
description: Add more hearts, etc.
website: https://gh05typlayz.com/

commands:
  addhearts:
    usage: /<command>
